version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "hmreumann" # Replace with your GitHub username
    assignees:
      - "hmreumann" # Replace with your GitHub username
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "hmreumann" # Replace with your GitHub username
    assignees:
      - "hmreumann" # Replace with your GitHub username
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "hmreumann" # Replace with your GitHub username
    assignees:
      - "hmreumann" # Replace with your GitHub username
    commit-message:
      prefix: "github-actions"
      include: "scope"